using Puzzles;

Console.WriteLine("Advent of Code 2022 Solutions in C#!");
Console.WriteLine();
Console.WriteLine($"Day One Part One: {DayOne.PartOne()}");
Console.WriteLine($"Day One Part Two: {DayOne.PartTwo()}");
Console.WriteLine();
Console.WriteLine($"Day Two Part One: {DayTwo.PartOne()}");
Console.WriteLine($"Day Two Part Two: {DayTwo.PartTwo()}");
Console.WriteLine();
Console.WriteLine($"Day Three Part One: {DayThree.PartOne()}");
Console.WriteLine($"Day Three Part Two: {DayThree.PartTwo()}");
Console.WriteLine();
Console.WriteLine($"Day Four Part One: {DayFour.PartOne()}");
Console.WriteLine($"Day Four Part Two: {DayFour.PartTwo()}");
Console.WriteLine();
Console.WriteLine($"Day Five Part One: {DayFive.PartOne()}");
Console.WriteLine($"Day Five Part Two: {DayFive.PartTwo()}");
Console.WriteLine();
Console.WriteLine($"Day Six Part One: {DaySix.PartOne()}");
Console.WriteLine($"Day Six Part Two: {DaySix.PartTwo()}");
Console.WriteLine();
Console.WriteLine($"Day Seven Part One: {DaySeven.PartOne()}");
Console.WriteLine($"Day Seven Part Two: {DaySeven.PartTwo()}");
Console.WriteLine();